#!/usr/bin/env bash
# One-shot setup for the uploader CLI (e.g. on your Mac): clones/updates the
# repo, installs the lightweight uploader-only Python dependencies (no
# sounddevice/soundfile -- nothing here plays or records audio), and runs
# the SFTP-only config wizard. Idempotent -- safe to re-run.
#
# Usage:
#   ./setup_uploader.sh [--dir <path>] [--repo-url <url>] [--reconfigure]
set -euo pipefail

REPO_URL="git@github.com:rocksynthetic/buckyball-chamber.git"
INSTALL_DIR="$HOME/buckyball-chamber"
RECONFIGURE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir) INSTALL_DIR="$2"; shift 2 ;;
    --repo-url) REPO_URL="$2"; shift 2 ;;
    --reconfigure) RECONFIGURE=true; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

echo "== Repository =="
if [[ -d "$INSTALL_DIR/.git" ]]; then
  echo "updating existing clone at $INSTALL_DIR"
  git -C "$INSTALL_DIR" pull --ff-only
else
  echo "cloning $REPO_URL into $INSTALL_DIR"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

echo "== Python environment =="
if [[ -d .venv && ! -x .venv/bin/pip ]]; then
  echo ".venv exists but is missing pip (likely from an interrupted previous run) -- recreating it"
  rm -rf .venv
fi
if [[ ! -d .venv ]]; then
  python3 -m venv .venv
fi
.venv/bin/pip install -q --upgrade pip
.venv/bin/pip install -q -r requirements-uploader.txt

echo "== Configuration =="
if [[ -f config.yaml && "$RECONFIGURE" != true ]]; then
  echo "config.yaml already exists, skipping the wizard (pass --reconfigure to redo it)"
else
  .venv/bin/python -m uploader.setup_wizard --out config.yaml
fi

echo "== chamber command =="
BIN_DIR="$HOME/.local/bin"
WRAPPER_PATH="$BIN_DIR/chamber"
mkdir -p "$BIN_DIR"
cat > "$WRAPPER_PATH" <<EOF
#!/usr/bin/env bash
# Generated by setup_uploader.sh -- runs the uploader CLI with this
# install's config.yaml, so you don't have to pass --config every time.
set -euo pipefail
args=("\$@")
has_config=false
for a in "\$@"; do
  if [[ "\$a" == --config || "\$a" == --config=* ]]; then
    has_config=true
    break
  fi
done
if [[ "\$has_config" == false ]]; then
  args+=(--config "$INSTALL_DIR/config.yaml")
fi
exec "$INSTALL_DIR/.venv/bin/python" -m uploader.upload_job "\${args[@]}"
EOF
chmod +x "$WRAPPER_PATH"
echo "wrote $WRAPPER_PATH"

path_note=""
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) path_note="
NOTE: $BIN_DIR isn't on your PATH yet. Add this to your shell's startup file
(~/.zshrc, ~/.bashrc, etc.) and open a new terminal:
  export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac

cat <<EOF

Setup done. From anywhere:
  chamber send my_track.wav       # upload and wait for the finished recording
  chamber upload my_track.wav     # upload only
  chamber download                # fetch the last upload's recording (waits if not ready)
$path_note
EOF
